name: Arduino Library Checks
on: [push, pull_request]
jobs:
  ArduinoLintjob:
    name: Run Arduino Lint
    env:
      compliance: strict
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
